# Generated by Django 3.0.5 on 2020-05-05 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_productcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='post',
            new_name='product',
        ),
    ]
